[package]
name = "multiread"
version = "0.1.0"
edition = "2024"

[dependencies]
cfg-if = "1.0.3"
memmap2 = "0.9.5"

[dev-dependencies]
criterion = "0.7.0"
pretty_assertions = "1.4.1"

[[bench]]
name = "read_speed"
harness = false
